name: Build Native Images

on:
  push:
    branches: [ "main", "release/**" ]
  pull_request:
    branches: [ "main", "release/**" ]
  release:
    types: [ published ]

jobs:
  run:
    name: "Package"
    uses: "./.github/workflows/native-build.yml"
    with:
      build: ./compiler/install
      test: ./compiler/test
      output-directory: ./compiler/bin
      meta-package: fpp
      fast-hack: true
    secrets: inherit
