name: Build Native Images
on:
  release:
    types: [published]
jobs:
  Build-Native-Images:
    strategy:
      matrix:
        os: ["ubuntu-18.04", "macos-10.15"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: "Checkout FPP Repository"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Image Build Step
      working-directory: ./compiler
      run: |
        . ${GITHUB_WORKSPACE}/.github/workflows/env-setup
        ./release
        mv native-fpp-*.tar.gz "${GITHUB_WORKSPACE}"
    - name: Publish Release Binaries
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ${GITHUB_WORKSPACE}/.github/workflows/publish native-fpp-*.tar.gz
  Build-PyPI-Package:
    needs: Build-Native-Images
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout FPP Repository"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Test PyPI
      uses: fprime-community/publish-pypi@main
      env:
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_CREDENTIAL }}
      with:
        package: "fprime-fpp"
        steps: "sdist"
    - name: PyPI
      uses: fprime-community/publish-pypi@main
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_CREDENTIAL }}
      with:
        repo: "pypi"
        package: "fprime-fpp"
        steps: "sdist"
